FROM debian:latest

RUN apt update -yq && apt upgrade && apt install curl gnupg2 -yq \
&& curl -sL https://deb.nodesource.com/setup_16.x | bash \
&& apt install nodejs -y \
&& apt clean -y

ADD . /app/

WORKDIR /app

RUN npm i

EXPOSE 4000

CMD npm run start
