name: Docker Image CI

on:
  push:
    branches: [article]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PAT_DOCKER }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push on les2api-${{github.ref_name}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.USERNAME_DOCKER }}/les2api-${{github.ref_name}}:latest
